@extends('admin.layouts.app')

@php
    $filterData = $filters->toArray();
    $kpis = $summary['kpis'] ?? [];
@endphp

@section('content')
    <div class="px-4 sm:px-0">
        @include('admin.analytics._page-header', [
            'title' => __('admin.analytics.pages.distribution.title'),
            'subtitle' => __('admin.analytics.pages.distribution.subtitle'),
        ])

        <section class="mb-6 rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
            <form method="GET" action="{{ route('admin.analytics.distribution') }}" class="space-y-4">
                <input type="hidden" name="preset" value="{{ $filters->preset }}">
                <div class="flex flex-wrap gap-2">@foreach (['7d', '30d', '90d'] as $preset)<button type="submit" name="preset" value="{{ $preset }}" class="inline-flex min-h-10 items-center rounded-md border px-3 text-sm font-semibold transition duration-[120ms] motion-reduce:transition-none active:scale-[.98] motion-reduce:active:scale-100 {{ $filters->preset === $preset ? 'border-slate-700 bg-slate-700 text-white' : 'border-gray-300 bg-white text-gray-700 hover:border-slate-400' }}" aria-pressed="{{ $filters->preset === $preset ? 'true' : 'false' }}">{{ __('admin.analytics.filters.'.$preset) }}</button>@endforeach</div>
                <div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
                    <div><label for="distribution-date-from" class="mb-1 block text-sm font-medium text-gray-700">{{ __('admin.analytics.filters.date_from') }}</label><input id="distribution-date-from" type="date" name="date_from" value="{{ $filterData['date_from'] }}" max="{{ now()->toDateString() }}" class="block min-h-10 w-full rounded-md border-gray-300 text-sm focus:border-slate-500 focus:ring-slate-500"></div>
                    <div><label for="distribution-date-to" class="mb-1 block text-sm font-medium text-gray-700">{{ __('admin.analytics.filters.date_to') }}</label><input id="distribution-date-to" type="date" name="date_to" value="{{ $filterData['date_to'] }}" max="{{ now()->toDateString() }}" class="block min-h-10 w-full rounded-md border-gray-300 text-sm focus:border-slate-500 focus:ring-slate-500"></div>
                    <div><label for="distribution-channel" class="mb-1 block text-sm font-medium text-gray-700">{{ __('admin.analytics.filters.channel') }}</label><select id="distribution-channel" name="channel_id" class="block min-h-10 w-full rounded-md border-gray-300 text-sm"><option value="">{{ __('admin.analytics.filters.all') }}</option>@foreach ($filterOptions['channels'] as $channel)<option value="{{ $channel->id }}" @selected($filters->channelId === (int) $channel->id)>{{ $channel->name }}</option>@endforeach</select></div>
                    <div><label for="distribution-status" class="mb-1 block text-sm font-medium text-gray-700">{{ __('admin.analytics.status') }}</label><select id="distribution-status" name="distribution_status" class="block min-h-10 w-full rounded-md border-gray-300 text-sm">@foreach (['all', 'synced', 'failed', 'pending'] as $status)<option value="{{ $status }}" @selected(($summary['status'] ?? 'all') === $status)>{{ __('admin.analytics.distribution_analytics.status.'.$status) }}</option>@endforeach</select></div>
                    <div><label for="distribution-task" class="mb-1 block text-sm font-medium text-gray-700">{{ __('admin.analytics.filters.task') }}</label><select id="distribution-task" name="task_id" class="block min-h-10 w-full rounded-md border-gray-300 text-sm"><option value="">{{ __('admin.analytics.filters.all') }}</option>@foreach ($filterOptions['tasks'] as $task)<option value="{{ $task->id }}" @selected($filters->taskId === (int) $task->id)>{{ $task->name }}</option>@endforeach</select></div>
                    <div><label for="distribution-category" class="mb-1 block text-sm font-medium text-gray-700">{{ __('admin.analytics.filters.category') }}</label><select id="distribution-category" name="category_id" class="block min-h-10 w-full rounded-md border-gray-300 text-sm"><option value="">{{ __('admin.analytics.filters.all') }}</option>@foreach ($filterOptions['categories'] as $category)<option value="{{ $category->id }}" @selected($filters->categoryId === (int) $category->id)>{{ $category->name }}</option>@endforeach</select></div>
                    <div class="xl:col-span-2"><label for="distribution-article" class="mb-1 block text-sm font-medium text-gray-700">{{ __('admin.analytics.filters.article') }}</label><select id="distribution-article" name="article_id" class="block min-h-10 w-full rounded-md border-gray-300 text-sm"><option value="">{{ __('admin.analytics.filters.all') }}</option>@foreach ($filterOptions['articles'] as $article)<option value="{{ $article->id }}" @selected($filters->articleId === (int) $article->id)>{{ $article->title }}</option>@endforeach</select></div>
                </div>
                <div class="flex justify-end"><button type="submit" name="preset" value="custom" class="inline-flex min-h-10 items-center rounded-md bg-slate-700 px-4 text-sm font-semibold text-white hover:bg-slate-800"><i data-lucide="filter" class="mr-2 h-4 w-4"></i>{{ __('admin.analytics.filters.apply') }}</button></div>
            </form>
        </section>

        <section class="grid grid-cols-2 gap-4 lg:grid-cols-5">@foreach ([['key' => 'total', 'icon' => 'send'], ['key' => 'synced', 'icon' => 'circle-check'], ['key' => 'failed', 'icon' => 'circle-x'], ['key' => 'pending', 'icon' => 'clock-3'], ['key' => 'success_rate', 'icon' => 'percent', 'suffix' => '%']] as $card)<article class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><p class="text-sm text-gray-500">{{ __('admin.analytics.distribution_analytics.kpi.'.$card['key']) }}</p><i data-lucide="{{ $card['icon'] }}" class="h-5 w-5 text-slate-600"></i></div><p class="mt-3 text-right font-mono text-3xl font-semibold tabular-nums text-gray-950">{{ $card['key'] === 'success_rate' ? number_format((float) ($kpis[$card['key']] ?? 0), 1) : number_format((int) ($kpis[$card['key']] ?? 0)) }}{{ $card['suffix'] ?? '' }}</p></article>@endforeach</section>

        <section class="mt-6 rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-semibold text-gray-950">{{ __('admin.analytics.distribution_analytics.trend') }}</h2><div class="mt-4">@include('admin.analytics._interactive-trend', ['series' => $summary['trend'] ?? [], 'chartLabel' => __('admin.analytics.distribution_analytics.trend'), 'metrics' => [['key' => 'total', 'label' => __('admin.analytics.distribution_analytics.kpi.total'), 'color' => '#334155'], ['key' => 'synced', 'label' => __('admin.analytics.distribution_analytics.kpi.synced'), 'color' => '#059669'], ['key' => 'failed', 'label' => __('admin.analytics.distribution_analytics.kpi.failed'), 'color' => '#dc2626'], ['key' => 'pending', 'label' => __('admin.analytics.distribution_analytics.kpi.pending'), 'color' => '#d97706']]])</div></section>

        <div class="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
            <section class="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm"><div class="p-5"><h2 class="text-lg font-semibold text-gray-950">{{ __('admin.analytics.distribution_analytics.channels') }}</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-5 py-3 text-left">{{ __('admin.analytics.filters.channel') }}</th><th class="px-5 py-3 text-right">{{ __('admin.analytics.distribution_analytics.kpi.total') }}</th><th class="px-5 py-3 text-right">{{ __('admin.analytics.distribution_analytics.kpi.synced') }}</th><th class="px-5 py-3 text-right">{{ __('admin.analytics.distribution_analytics.kpi.failed') }}</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse (($summary['channels'] ?? []) as $row)<tr><td class="px-5 py-3 font-medium text-gray-900">{{ $row['name'] }}</td><td class="px-5 py-3 text-right font-mono tabular-nums">{{ $row['total'] }}</td><td class="px-5 py-3 text-right font-mono tabular-nums">{{ $row['synced'] }}</td><td class="px-5 py-3 text-right font-mono tabular-nums">{{ $row['failed'] }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-gray-500">{{ __('admin.analytics.no_data') }}</td></tr>@endforelse</tbody></table></div></section>
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold text-gray-950">{{ __('admin.analytics.distribution_analytics.issues') }}</h2><a href="{{ route('admin.distribution.jobs') }}" class="text-sm font-semibold text-blue-600 hover:text-blue-700">{{ __('admin.dashboard.view_all') }}</a></div><div class="mt-4 space-y-3">@forelse (($summary['issues'] ?? []) as $row)<article class="rounded-lg border border-gray-100 p-4"><div class="flex items-center justify-between gap-3"><span class="truncate text-sm font-medium text-gray-900">{{ $row->article_title }}</span><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $row->status === 'failed' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700' }}">{{ __('admin.analytics.distribution_analytics.status.'.($row->status === 'synced' ? 'synced' : ($row->status === 'failed' ? 'failed' : 'pending'))) }}</span></div><p class="mt-1 text-xs text-gray-500">{{ $row->channel_name }} · {{ $row->created_at }}</p>@if ($row->last_error_message)<p class="mt-2 line-clamp-2 text-sm text-red-600">{{ $row->last_error_message }}</p>@endif</article>@empty<p class="rounded-lg bg-gray-50 p-4 text-sm text-gray-500">{{ __('admin.analytics.no_data') }}</p>@endforelse</div></section>
        </div>
    </div>
@endsection
